### ISSUE TITLE
Crash on AFVpnService.onCreate()

### ISSUE THREAD

**Issue by lixiaoyi** [AnchorFreePartner/hydrasdk-demo-android#35] opened 2020-03-02 09:46 UTC
Hello, we have a production crash on all android versions, when using:

> com.github.AnchorFreePartner.hydra-sdk-android:sdk:3.1.0
> com.github.AnchorFreePartner.hydra-sdk-android:openvpn:3.1.0

We don't have much information about what is wrong, could you please help ?

```
Fatal Exception: java.lang.RuntimeException: Unable to create service com.anchorfree.vpnsdk.vpnservice.AFVpnService: java.lang.NullPointerException
       at android.app.ActivityThread.handleCreateService + 3851(ActivityThread.java:3851)
       at android.app.ActivityThread.access$1500 + 229(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage + 1887(ActivityThread.java:1887)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 226(Looper.java:226)
       at android.app.ActivityThread.main + 7210(ActivityThread.java:7210)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 576(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main + 956(ZygoteInit.java:956)
```

```
Caused by java.lang.NullPointerException
       at com.anchorfree.toolkit.utils.ObjectHelper.checkNotNull + 65(ObjectHelper.java:65)
       at com.anchorfree.toolkit.utils.ObjectHelper.requireNonNull + 42(ObjectHelper.java:42)
       at com.anchorfree.toolkit.utils.ObjectHelper.requireNonNull + 27(ObjectHelper.java:27)
       at com.anchorfree.vpnsdk.vpnservice.config.VpnConfigController.readCurrentVpnConfig + 144(VpnConfigController.java:144)
       at com.anchorfree.vpnsdk.vpnservice.config.VpnConfigController.readCurrentVpnConfigAndNotifyListener + 119(VpnConfigController.java:119)
       at com.anchorfree.vpnsdk.vpnservice.config.VpnConfigController.registerChangeListener + 105(VpnConfigController.java:105)
       at com.anchorfree.vpnsdk.vpnservice.AFVpnService.onCreate + 239(AFVpnService.java:239)
       at android.app.ActivityThread.handleCreateService + 3839(ActivityThread.java:3839)
       at android.app.ActivityThread.access$1500 + 229(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage + 1887(ActivityThread.java:1887)
       at android.os.Handler.dispatchMessage + 106(Handler.java:106)
       at android.os.Looper.loop + 226(Looper.java:226)
       at android.app.ActivityThread.main + 7210(ActivityThread.java:7210)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 576(RuntimeInit.java:576)
       at com.android.internal.os.ZygoteInit.main + 956(ZygoteInit.java:956)
```

**Comment by timoshenkoav** [comment] 2020-03-02 14:02
Hello!
Thanks for the report, we are aware of this issue. will be fixed in upcoming release

**Comment by lixiaoyi** [comment] 2020-03-09 10:27
Hey, when do you think the upcoming release with this fix ?
It is impacting us more than 30 users per day.

**Comment by timoshenkoav** [comment] 2020-03-09 21:34
expect to release this week

**Comment by timoshenkoav** [comment] 2020-03-20 18:22
please update to sdk 3.1.2

**Closed by timoshenkoav** 2020-03-20 18:22 UTC

**Comment by zohaib1sahni** [comment] 2022-04-20 17:04
Caused by: java.lang.NullPointerException
        at com.anchorfree.toolkit.utils.ObjectHelper.checkNotNull(ObjectHelper.java:65)
        at com.anchorfree.toolkit.utils.ObjectHelper.requireNonNull(ObjectHelper.java:42)
        at com.anchorfree.toolkit.utils.ObjectHelper.requireNonNull(ObjectHelper.java:27)
        at com.anchorfree.sdk.UnifiedSDKGlobal.getInstance(UnifiedSDKGlobal.java:132)
        at com.anchorfree.sdk.UnifiedSDKGlobal.update(UnifiedSDKGlobal.java:116)
        at com.anchorfree.sdk.UnifiedSDK.update(UnifiedSDK.java:46)
        at com.vpn.master.app.proxy.app_utils.VpnApplication.initializeVpnHydraSdkForApp(VpnApplication.kt:92)
        
        
        Still getting this error
